[package]
name = "ritw"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
nalgebra = "0.30.0"
rand = "0.8.4"
